# Site settings
title: Esteban Irurueta
email: esteban@irurueta.net
url: https://irurueta.net
description: "My personal site for resume and for Irurueta.net placeholder. Lazy to use an actual CMS."
keywords: "esteban, irurueta, esteban@irurueta.net, office365, office, microsoft, work, resume, etc"
skills: "Systems Engineer - Office 365 - Systems Administrator - Data"
meta_author: Irurueta Esteban

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/irurueta/
  - title: facebook
    url: http://facebook.com/esuiru
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/esuiru
  - title: bitbucket
    url: http://bitbucket.org/esuiru
  - title: github
    url: http://github.com/esuiru

# Postal address (add as many lines as necessary)
address:
  - line: Tampa, FL 33602 
  - line: esteban@irurueta.net 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
